### ISSUE TITLE
Add build test on PR using github CICD actions.  

### ISSUE THREAD

**Issue by anisharaz** [blockx3/imp#1]
Create a github action that runs on every pull request and tests the code by building it. Command to build the project is `npm run build`.

**Comment by akadeepesh** [comment]
I'm willing to do this, just confirm me once if I only need to check for build

**Comment by anisharaz** [comment]
@akadeepesh Yes, For now only need to check for build. And also please set the `standalone` output mode in next.config.mjs

**Comment by akadeepesh** [comment]
Sure
