### ISSUE TITLE
Add Dialog UI

### ISSUE THREAD

**Issue by anisharaz** [blockx3/imp#17]
### Add a shadcn UI Dialog on clicking the post.
The content inside the dialog will be empty for now.
NOTE ->  No need to setup database to work on this issue.

ref: https://ui.shadcn.com/docs/components/dialog

![image](https://github.com/user-attachments/assets/94881761-c205-4fc0-ad95-317752429a9a)

**Comment by saadii00** [comment]
Can you please assign it to me. I would love to work on it.

**Comment by anisharaz** [comment]
@saadii00 done

**Comment by saadii00** [comment]
https://github.com/blockx3/imp/pull/18
Kindly review and merge it. 🙂
