### ISSUE TITLE
App LOGO

### ISSUE THREAD

**Issue by anisharaz** [blockx3/imp#4]
Based on the idea of the project create LOGO for the app.

**Comment by biplab-sutradhar** [comment]
@anisharaz is this issue still open

**Comment by biplab-sutradhar** [comment]
@anisharaz I want to contribute to this repo so will you create more issues

**Comment by anisharaz** [comment]
@biplab-sutradhar for sure , i am just setting up the bits and bytes for the project to start. I will start adding the issues now.
