### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by anisharaz** [blockx3/imp#8]
### Create a multistage docker file. Try to make the image size as minimal as possible.

Guidelines:
- Make sure to run `npx prisma generate` before running `npm run build` in Dockerfile. or else the docker build will fail in future commits.
- The project uses `standalone` mode in nextjs. Make sure to create the docker file accordingly.

**Comment by geekyharsh05** [comment]
@anisharaz Can you please assign me?
